export const EMPTY_SECOND_OPERAND_ERROR_MESSAGE =
  '2번째 피연산자를 입력해주세요.';

export const INFINITY_ERROR_TEXT = '오류';

export const CALCULATOR_DATA_KEY = 'calculatorData';

export const OPERATOR = {
  PLUS: '+',
  MINUS: '-',
  MULTIPLY: 'X',
  DIVIDE: '/',
  EQUAL: '=',
};

export const FIXED_POINT_LENGTH = 2;

export const CALCULATOR_NUMBER_LIST = [9, 8, 7, 6, 5, 4, 3, 2, 1, 0];

export const CALCULATOR_OPERATOR_LIST = [
  OPERATOR.DIVIDE,
  OPERATOR.MULTIPLY,
  OPERATOR.MINUS,
  OPERATOR.PLUS,
  OPERATOR.EQUAL,
];

export const CALCULATOR_ARITHMETIC_OPERATOR_LIST = [
  OPERATOR.DIVIDE,
  OPERATOR.MULTIPLY,
  OPERATOR.MINUS,
  OPERATOR.PLUS,
];
