const MAX_NUMBER_LENGTH = 3;
const INDIVISIBLE_NUMBER = '0';

const RESULT = {
  ERROR_MESSAGE: '오류',
  RESET: '0',
};

const DIGIT_LIST = [9, 8, 7, 6, 5, 4, 3, 2, 1, 0];

export { MAX_NUMBER_LENGTH, INDIVISIBLE_NUMBER, RESULT, DIGIT_LIST };
